## Testes de Hipotese e mais
- Anotações
    - Falta codar:
        - Distribuições de probabilidade
        - Estatística descritiva mais elaborada

In [ ]:
import pandas as pd
from cinza.Estats import *

### Teste t uma amostra

O setor de suporte da empresa afirma que o tempo de resolução de chamados de suporte é de 30 minutos em média. No entanto, alguns clientes fizeram reclamações, dizendo que esse tempo é maior.
Você coleta uma amostra, na qual anotou os minutos de resolução de vários chamados de suporte, para realizar um teste de hipóteses.

**Dados coletados**:
Analisando 30 chamados de suporte, a média é de 34 minutos, com desvio padrão de 7.30 minutos.

In [ ]:
path: str = r"data/amostra_chamados.xlsx"
df = pd.read_excel(path)

In [ ]:
df.head(5)

In [ ]:
df.describe()

In [ ]:
v_boxplot(df, ["tempo_resolucao"])

In [ ]:
val = tt_uma_amostra(df, "tempo_resolucao", float(30), tipo=">")
val

### Teste t para duas amostras independentes - presumindo variâncias diferentes:

In [ ]:
path: str = r"data/Testes t.xlsx"
df = pd.read_excel(path)

In [ ]:
df.head(5)

In [ ]:
val = tt_duas_amostras_independentes_var_diferentes(df, "PETR4", "VALE3")
val

- boxplot das variaveis

In [ ]:
v_boxplot(df, ["PETR4", "VALE3"])

In [ ]:
df.describe()

In [ ]:
val = teste_normalidade(df, ["PETR4", "VALE3"])
val

### Teste t para duas amostras pareadas

In [ ]:
path: str = r"data/Testes t.xlsx"
df = pd.read_excel(path, sheet_name=1)

In [ ]:
df.head(5)

In [ ]:
df.describe()

In [ ]:
tt_duas_amostras_pareadas(df, "Vendas_Antes", "Vendas_Depois", tipo="<")

In [ ]:
v_histogram(df, ["Vendas_Antes", "Vendas_Depois"], bins=10)

### Teste z para uma amostra

 A varejista Magazine Luiza quer avaliar se a taxa de devolução de um determinado fabricante é maior que 7%. A
empresa coleta uma amostra aleatória de pedidos e calcula a proporção de devoluções. Utilizando o teste z, a empresa
verifica se há evidências estatísticas suficientes para concluir que a taxa de devolução é significativamente maior do que
7%

In [ ]:
path: str = r"data/magalu.xlsx"
df = pd.read_excel(path)

In [ ]:
df.head(5)

In [ ]:
df.describe()

In [ ]:
val = tz_uma_amostra(df, "devolvido", 0.07, tipo=">")
val

### Teste z para duas amostras (proporções)

Uma empresa de marketing deseja comparar a eficácia de duas páginas diferentes em converter visitantes do site em
clientes. Ao coletar os dados, observaram:
Página A (página antiga) : 3000 visitantes, 240 conversões
Página B (página nova) : 3200 visitantes, 291


H0: A proporção de conversão da página antiga (Página A) é maior ou igual à proporção de conversão da página nova
(Página B).

Ha: A proporção de conversão da página antiga (Página A) é menor do que a proporção de conversão da página nova
(Página B)

In [ ]:
path: str = r"data/paginas.xlsx"
df = pd.read_excel(path)

In [ ]:
df.head(5)

In [ ]:
df.describe()

In [ ]:
val = tz_duas_amostras(df, "Pagina A", "Pagina B", tipo="<")
val

In [ ]:
v_histogram(df, ["Pagina A", "Pagina B"])

### Tamanho da amostra para a proporção e média

In [ ]:
df = pd.read_excel("data/Testes t.xlsx", sheet_name=1)
df.head(5)

- para proporção

In [ ]:
val = tamanho_amostras_proporcao_AB(taxa_base=0.05, taxa_variante=0.0535, alfa=0.05, poder=0.90)
val

- para médias independentes

In [ ]:
val = tamanho_amostra_media_AB(0.015, 0.002, 0.05, 0.9)
val

- para médias pareadas

In [ ]:
val = tamanho_amostra_media_AB_pareada(
    df, ["Vendas_Antes", "Vendas_Depois"],
    diferenca_minima=5, alfa=0.05, poder=0.80
)
val

### Testes de Suposição
- Shapiro–Wilk test
- Kolmogorov–Smirnov test
- Anderson–Darling test
- levene

In [ ]:
from cinza import Estats as stt
df = pd.read_excel("data/anova.xlsx")
df.head(5)

#### Visualizando assimetria, normalidade e variancias
- Describe
- QQ plot
- Variance Analises
- Histplot

In [ ]:
df.describe()

In [ ]:
v_QQ_plot(df, ["A", "B", "C", "D"], residual=True)

In [ ]:
v_analise_variancia(df)

In [ ]:
v_histogram(df, ["A", "B", "C", "D"], bins=10)

#### Testes
- Normalidade
- Heterogeneidade das variâncias

In [ ]:
teste_normalidade(df, ["A", "B", "C", "D"])

In [ ]:
teste_levene(df, colunas=["A", "B", "C", "D"])

### Testes de ANOVA
- 1 fator
- 2 fator SEM interação / repetição
- 2 fator COM interação / repetição

##### ANOVA 1 fator

In [ ]:
from cinza import Estats as stt
df = pd.read_excel("data/anova.xlsx")
df2 = pd.read_excel("data/ANOVA 1 fator.xlsx")


display(
    df.head(),
    df2.head()
)

In [ ]:
# ANOVA 1 fator variaveis em colunas
teste_anova_1_fator(df, ["A", "B", "C", "D"])

In [ ]:
# ANOVA 1 fator variaveis em um unica coluna
teste_anova_1_fator(df2, "Grupo", target="Vendas")

In [ ]:
v_analise_variancia(df2, "Grupo", target="Vendas", dp=False, mediana=True, ic=True)

##### ANOVA 2 fator SEM interação

In [ ]:
from cinza import Estats as stt
df = pd.read_excel("data/ANOVA 2 fatores.xlsx")

df.head()

In [ ]:
# anova 2 fatores
teste_anova_2_fator(df, ["Cargo", "Área"], target="Salario")

In [ ]:
# grafico de interação
v_interacao_posHoc(df, x="Área", hue="Cargo", y="Salario")
v_interacao_posHoc(df, x="Cargo", hue="Área", y="Salario")

##### ANOVA 2 fator COM interação

In [ ]:
from cinza import Estats as stt
df = pd.read_excel("data/ANOVA 2 fatores.xlsx")
df.head()

In [ ]:
teste_anova_2_fator_interacao(df, ["Cargo", "Área"], target="Salario")

In [ ]:
# comparação pós-hoc de tukey
comparacao_posHoc_tukey(df, ["Cargo" ,"Área"], target="Salario", all=False)

In [ ]:
# grafico de interação
v_interacao_posHoc(df, x="Área", hue="Cargo", y="Salario")
v_interacao_posHoc(df, x="Cargo", hue="Área", y="Salario")

### Teste do Qui-Quadrado   (não paramétrico)
O teste qui-quadrado é uma técnica estatística utilizada para verificar se existe uma associação significativa entre duas
variáveis categóricas (qualitativas). Ele avalia se a distribuição das frequências observadas em uma tabela de contingência
difere significativamente das frequências esperadas, assumindo que não há associação entre as variáveis.

Esse teste é amplamente usado para analisar tabelas de contingência, onde são comparadas as frequências observadas
de diferentes categorias de duas variáveis. O resultado nos permite inferir se há uma relação estatisticamente significativa
entre as categorias das variáveis analisadas

In [5]:
from cinza.Estats import *
df = pd.read_excel("data/qui-quadrado.xlsx")
df.head()

   Cliente    Faixa de Renda Tipo de Conteúdo
0        1  Menos de $25,000            Filme
1        2  Menos de $25,000            Filme
2        3  Menos de $25,000            Filme
3        4  Menos de $25,000            Filme
4        5  Menos de $25,000            Filme

In [6]:
r = teste_qui_quadrado(df, "Faixa de Renda", "Tipo de Conteúdo", rp_abs_min=1.9)

In [7]:
r["resultado"]

           result
X²        39.1059
gl         4.0000
N        555.0000
p-valor    0.0000

Nosso p-valor do qui-quadrado é inferior à 5% (alfa), logo rejeitamos a hipotese nula
- H0: as categorias são independentes
- H1: as categorias NÃO são independentes

In [8]:
r["tabela"]

                  Filme  E Filme  RP Filme  Série  E Série  RP Série
Faixa de Renda
$25,000 a $49,99     38    52.17     -1.96     76    61.83      1.80
$75,000 a $99,99     59    41.65      2.69     32    49.35     -2.47
Menos de $25,000     26    44.85     -2.81     72    53.15      2.59

É possível observar, a partir dos resultados apresentados, que:

* Indivíduos com faixa salarial anual entre 75.000 e 99.999 tendem a apresentar maior preferência por filmes;
* Pessoas com renda anual inferior a 25.000 tendem a preferir séries;
* Essa tendência também é observada entre indivíduos com faixa salarial anual entre 25.000 e 49.999, que demonstram maior preferência por séries.

Conclui-se, portanto, que indivíduos pertencentes às menores faixas salariais apresentam uma tendência maior de preferência por séries, enquanto faixas salariais mais elevadas demonstram maior preferência por filmes.

### Teste do Qui-Quadrado - ajustamento  (não paramétrico)
* N eventos

In [9]:
from cinza.Estats import *
df = pd.read_excel("data/Canditados.xlsx")
df

   Candidato  f absoluta
0     Felipe         129
1  Marininha          76
2    Zezinho          95

In [10]:
r = teste_qui_quadrado_ajustamento(df, coluna_categoria="Candidato", coluna_frequencia="f absoluta")

In [11]:
r["resultado"]

          resultado
X²        14.420000
gl         2.000000
N        300.000000
p-valor    0.000739

De acordo com teste do qui-quadrado acima podemos observar que há diferenças significativas nas intenções de voto para os candidatos

In [12]:
r["tabela"]

   Candidato  Observado  Esperado  Proporção   RP
0     Felipe        129     100.0     0.4300  2.9
1  Marininha         76     100.0     0.2533 -2.4
2    Zezinho         95     100.0     0.3167 -0.5

Ao que podemos observar na tabela de frequências, o candidato Felipe possui mais intenções de voto do que seus opositores

### Correlação de Pearson
A correlação e Pearson é um teste Paramétrico de correlação

In [ ]:
from cinza.Estats import *
df = pd.read_excel("data/correlacao.xlsx")
df.head()

Em casos em que as variáveis passam no teste de normalidade (Shapiro), usamos a correlação de Pearson

In [ ]:
correlacao_pearson(df, ["Salario", "Tempo de empresa", "Felicidade"])

### Correlação de Spearman  (não paramétrico)
A correlação e Spearman é um teste Não-Paramétrico de correlação

In [ ]:
from cinza.Estats import *
df = pd.read_excel("data/correlacao.xlsx")
df.head()

In [ ]:
correlacao_spearman(df, ["Salario", "Tempo de empresa", "Felicidade"])

### Teste do sinal (não paramétrico)
O teste utilizado para comparar amostras ordinais pareadas é o teste do sinal. Esse teste é uma versão não paramétrica,
pois lida com variáveis ordinais, onde não é possível assumir normalidade.

Dados ordinais são categorizados em uma ordem (por exemplo, "Ruim", "Bom", "Muito bom", "Excelente"), mas as
diferenças entre as categorias são difíceis de quantificar matematicamente. Isso ocorre porque, em dados ordinais, a
magnitude da diferença entre as categorias não é necessariamente uniforme ou conhecida.

Nesses casos, utilizamos o teste do sinal para verificar se existe uma diferença significativa na população, observando se
as direções das diferenças entre os pares de observações sugerem uma mudança consistente.

In [15]:
from cinza.Estats import *
df = pd.read_excel("data/teste_do_sinal.xlsx")
df.head()

     Usuario  Nota_Versao_Antiga  Nota_Versao_Nova
0  Usuario 1                   3                 4
1  Usuario 2                   1                 3
2  Usuario 3                   4                 4
3  Usuario 4                   2                 3
4  Usuario 5                   2                 2

Testando se a versão NOVA é "melhor" que a versão antiga

In [16]:
teste_do_sinal(df, ["Nota_Versao_Antiga", "Nota_Versao_Nova"], tipo=">", alfa=0.05)

                 result
N                    30
Qtd +                12
Qtd -                 5
Válidos              17
p(+)             0.7059
p-valor        0.071732
Decisão  Não rejeita H0

Testando se a versão ANTIGA é "melhor" que a versão nova

In [17]:
teste_do_sinal(df, ["Nota_Versao_Antiga", "Nota_Versao_Nova"], tipo="<", alfa=0.05)

                 result
N                    30
Qtd +                12
Qtd -                 5
Válidos              17
p(+)             0.7059
p-valor        0.975479
Decisão  Não rejeita H0

Testando se existe diferença entre as duas versões (!=)

In [ ]:
teste_do_sinal(df, ["Nota_Versao_Antiga", "Nota_Versao_Nova"], tipo="!=", alfa=0.05)

### Teste do McNemar (não paramétrico)
Para comparar as proporções de duas amostras pareadas, utilizamos o teste de McNemar. Esse teste é ideal para avaliar
se há diferença significativa entre as proporções de dois grupos em amostras pareadas, sendo muito comum em análises
de "antes e depois" ou quando os sujeitos são emparelhados.

Hipóteses do Teste de McNemar:
* Ho: As proporções de sucessos são iguais entre os grupos.
* Ha: As proporções de sucessos são diferentes entre os grupos.

        Amostras pareadas (proporções)
        Variaveis Binarias
        tabela de contigencia (2x2)

In [5]:
from cinza.Estats import *
df = pd.read_excel("data/dados_mcnemar_politica.xlsx")
df.head()

     Funcionario  Antes_Politica Depois_Politica
0  Funcionario 1      Satisfeito  Não Satisfeito
1  Funcionario 2  Não Satisfeito  Não Satisfeito
2  Funcionario 3  Não Satisfeito      Satisfeito
3  Funcionario 4  Não Satisfeito      Satisfeito
4  Funcionario 5      Satisfeito  Não Satisfeito

In [6]:
# teste de McNemar (sem correção de continuidade)
r = teste_de_mcNemar(df, ["Antes_Politica", "Depois_Politica"], alfa=0.05, correcao=False)

In [7]:
r["tabela"]

Depois_Politica  Não Satisfeito  Satisfeito  Total
Antes_Politica
Não Satisfeito               65          51    116
Satisfeito                   29          55     84
Total                        94         106    200

In [8]:
r["resultado"]

                result
X²                6.05
gl                 1.0
p-value         0.0139
N                200.0
Conclusão  Rejeitar H0

### Fim